name: StorybookInteractive
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.BtmProduction
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: 4.5.0
targets:
  StorybookInteractive:
    type: application
    platform: iOS
    info:
        path: StorybookInteractive/Info.plist
        properties:
            NSCameraUsageDescription: "Nyalakan kamera untuk memindai kartu"
            UIApplicationSceneManifest:
                UIApplicationSupportsMultipleScenes: false
                UISceneConfigurations:
                    UIWindowSceneSessionRoleApplication:
                      - UISceneConfigurationName: "Default Configuration"
                        UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    sources: [StorybookInteractive]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.BtmProduction.StorybookInteractive
      INFOPLIST_FILE: StorybookInteractive/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
        - package: Lottie
  StorybookInteractiveTests:
    type: bundle.unit-test
    platform: iOS
    sources: [StorybookInteractiveTests]
    dependencies:
      - target: StorybookInteractive
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/StorybookInteractive.app/StorybookInteractive"
        BUNDLE_LOADER: "$(TEST_HOST)"
        INFOPLIST_FILE: StorybookInteractive/Info.plist
        GENERATE_INFOPLIST_FILE: true
schemes:
  StorybookInteractive:
    build:
      targets:
       StorybookInteractive: all
       StorybookInteractiveTests: all
    test:
      targets:
      - name: StorybookInteractiveTests
      gatherCoverageData: true
