name: StorybookInteractive
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.BtmProduction
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: 4.5.0
targets:
  StorybookInteractive:
    type: application
    platform: iOS
    sources: [StorybookInteractive]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.BtmProduction.StorybookInteractive
      INFOPLIST_FILE: StorybookInteractive/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
        - package: Lottie
schemes:
  StorybookInteractive:
    build:
      targets:
       StorybookInteractive: all
